name: Merge English Dictionaries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: en_dicts
          key: en-dicts-${{ runner.os }}-${{ hashFiles('**/en_merge.dict.yaml') }}-${{ github.run_id }}

      - name: Merge dictionaries
        run: python en_merge.py

      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code && echo "changes=false" >> $GITHUB_OUTPUT || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add config.json
          git commit -m 'Update merged dictionaries'
          git push

      - name: Create release
        if: steps.changes.outputs.changes == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          name: Nightly Release
          body: 'Automated nightly release of merged English dictionaries'
          files: |
            en_merge.dict.yaml
            config.json